### ISSUE TITLE
Question: FTP connections.

### ISSUE THREAD

**Issue by Anach** [Oops19/TS4-PrivacyProtector#1]
Thanks for this mod! 

The other day, I noticed some ports I had open for some other software on my router, were being accessed by TS4, and being blocked by my local firewall. This has helped me to see what's connecting where, so I can align those IP addresses in Europe with the mods I have installed.

However, I noticed one particularly popular mod, appears to open an FTP connection, which concerns me more than the others. Have you had any experience with certain mods using FTP connections in TS4 - Is this a normal thing for modders to do in TS4?

**Comment by Oops19** [comment]
I'm aware of one mod author who uses FTP instead of HTTP to track the usage of their mods and the geo-location of the users.
I didn't look into the details which data is exchanged as the mod is obfuscated.
I assume they use it also for a version check as the mod usually breaks when EA releases a TS4 update.

Responsible mod authors would make this as an optional feature one can activate to check for updates manually or weekly and not every time the game starts without any information for the user and/or option to opt-out.
